# -*- coding: utf-8 -*-
"""Assessment-day-15

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iUtf1wYEbw9CaUFRKl7e0zaJlLagJ_qp
"""

num = int(input("Enter a number: "))  
sum = 0  
temp = num  
  
while temp > 0:  
   digit = temp % 10  
   sum += digit ** 3  
   temp //= 10  
  
if num == sum:  
   print(num,"is an Armstrong number")  
else:  
   print(num,"is not an Armstrong number")